(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.createjsTest08 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{move:0,title:31},true);

	// timeline functions:
	this.frame_36 = function() {
		this.stop();
		if(this.onAnimeEnd) { this.onAnimeEnd(this); }
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(36).call(this.frame_36));

	// title
	this.instance = new lib.grTitle("synched",0);
	this.instance.setTransform(-197.5,363,1,1,0,0,0,189.5,20.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25).to({startPosition:0,_off:false},0).to({x:334.4,y:362.1},4).wait(1).to({x:330.1},0).wait(1).to({startPosition:0},0).wait(6));

	// jack
	this.JackMC = new lib.mcJackLantern();
	this.JackMC.setTransform(320.1,200.1,1,1,0,0,0,-20.6,21.3);

	this.timeline.addTween(cjs.Tween.get(this.JackMC).to({x:348.7,y:-129.8},12).wait(1).to({x:351.1,y:530.3},0).to({x:320.1,y:200.1},12).wait(12));

	// base button
	this.ButtonMC = new lib.mcButtonBase();
	this.ButtonMC.setTransform(320,200);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.ButtonMC}]}).wait(37));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,640,400);


// symbols:
(lib.grTitle = function() {
	this.initialize();

	// レイヤー 14
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F39800").s().p("AdmAcIgDClIhXAAIAIhgQAEgyAAgdQAAgfgNgEQgNgEgQAJQgVANgDACQgSAOgKAQQgFAegDAmIgDBcIhNAAIAckUIBHAGIgCAeQArgiAmAAQAmAAASARQATATAEAUQADATAAAiIAAAAAZCAsIhJgBQAHgZgFgHQgHgKgSATIglAxIgIB6IhLADIAZkTIBJAAIgIBAQASgVAUgTQAbgYAWgCQASgCANANQAPAPACAeQACAbgLAsIAAAAAVHBKIiPAIQgEATAGARQAFAQAQAGQAXAJAYgNQAMgFAZgeIAeAgQggAuglAOQgcAJgegGQgigFgTgVQgTgVgDgfQgGgoAGgcQAOhJAmggQAagWAegGQAsgHAdAUQAmAbAAAwQAAAkgLAhIAAAAATRgMQgJAMgGAhIBJgCQADgZgBgMQgCgWgNgGQgbgLgSAhIAAAAAPmjCIBJAGIgSCYIA/AAIAAA0IhDAEIgICrIhSAAIAJiiIg5AKIAFhHIA8gCIAWigAN2gZQADATAAAiIgDClIhXAAIAHhgQAFgyAAgdQAAgfgNgEQgNgEgQAJQgVANgDACQgSAOgLAQQgFAegCAmIgDBcIhNAAIAckUIBHAGIgCAeQArgiAlAAQAnAAASARQATATAEAUIAAAAAIdgRQgGgPgVAFQgNAEgYAVIgvgqQAjgdAOgEQAcgLAaADQAlAFATAdQAJANAFAaQADAdgCAjIgHCJIhUAEIALgiQgnAegVAFQgkAKgcgeQgRgTAAgpQAAgiATgcQAagnApgGQATgCATAGQAMADAUARQAGgkgEgMIAAAAADgi+IgPElICWgCIgCBWIjlALIATmGIBNACAHjCDQAPgDAPgJQAegRgMgYQgJgPgRAAQgIAAgOAIQgXALgEAWQgCAPAKAIQAHAFAMgBIAAAAAA3AdQh3AGhEAIIAAgmIC7gEIAAAcAjPilQgEALgNATIgKALIgNgEIAIgRQgXgGAAgYQAAgRARgFQATgGALALQALAKgDARIAAAAAkkgMQAJAngFAsQgGAqgUAhQgZAkglALQgjAJgbgEQgvgGgWgfQgZghAGhGQAGg/AlgoQAggkA4gCQBSgDAVBKIAAAAAmtgOQgbAmAFBBQAEAzAaAIQAaAHARggQAJgSAEguQABgegBgaQgCgWgPgIQgcgNgTAaIAAAAApZAdQh4AGhFAIIAAgmIC9gEIAAAcAuJiRIAtA8IhhBlIBaCNIhAArQgYgsgZgmQgjgzgVgiIAAChIhagBIAYmGIBRALIgPCwICDiHAyBgXQAFAUgHAfIg/gCIACgcQgCgVgNgCQgPgCgPAPQgPANgGAZQgKAjACAXQACAeAMAHQAYATAYgPQAPgJAbgeIAhAcQgRAegPAPQgSATgcAJQgeAJgggHQgggIgTgeQglg5AihdQAahDAygPQA4gRAoAgQAUARACAaIAAAAA2ygRQgGgPgVAFQgOAEgXAVIgvgqQAigcAPgFQAcgLAaADQAlAGATAcQAJAPAFAYQADAXgCApIgHCJIhUAEIALgiQgoAegUAFQgkAKgcgeQgRgTAAgpQAAgiATgcQAagnApgGQATgCATAGQANAEATAQQAFgkgDgMIAAAAA27BOQgKgPgRAAQgHAAgPAIQgXALgDAWQgDAPAKAIQAHAFAMgBQAPgDAPgJQAegQgLgZIAAAAA5vAnQgKBkg2AjQgeAUgmACQgjACgXgLQgggPgLgeQgKgZgDgpIBNgDQACAjAUALQAPAKATgLQATgLALgkQAJggAAhHIACiiIBPACIAAB6QAAAggHBNIAAAA").cp();
	this.shape.setTransform(189.5,20.1);

	// レイヤー 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#601986").s("#601986").ss(16.1).p("AbZgIQgSAMgLAQQgFAegCAlIgEBcIhNAAIAckTIBIAFIgCAeQArgiAlAAQAnAAASARQATATADAVQAEATAAAhIgEClIhWAAIAHhgQAEgxAAgdQAAgggNgEQgNgDgPAJQgVAOgDADIAAAAAZEAfIhJgCQAIgYgGgGQgHgJgRARIgmAwIgHB6IhLAEIAYkUIBJAAIgHBAQARgVAUgSQAbgZAWgBQASgDAOAOQAOAOADAfQABAbgLAsIAAAAAVJA9IiOAHQgEATAGARQAFARAPAGQAXAJAYgNQANgFAZgfIAeAgQghAvglANQgbAKgfgGQgigGgSgUQgUgVgDggQgGgnAGgcQAPhKAmgfQAZgXAfgFQArgIAeAVQAlAaAAAzQAAAigLAhIAAAAATEAUIBJgCQAEgXgCgPQgCgWgNgGQgbgLgSAiQgIANgHAgIAAAAAQbAHIgHCqIhTAAIAKihIg5AJIAEhHIA8gCIAXifIBJAGIgTCXIBAAAIAAA1IhEAEAMEgZQgVAOgDADQgSAMgLAQQgFAegCAlIgEBcIhNAAIAckTIBIAFIgCAeQArgiAlAAQAnAAASARQATATADAVQAEATAAAhIgEClIhWAAIAHhgQAEgxAAgdQAAgggNgEQgNgDgPAJIAAAAAIfgfQgGgOgUAFQgNAEgZAUIgugpQAjgdANgFQAdgLAaAEQAlAFATAcQAIANAFAbQAEAcgCAjIgICJIhUAEIALgiQgnAegVAGQgjAJgcgeQgRgSAAgqQAAgiASgcQAbgmApgFQASgBATAFQANACATARQAGglgEgMIAAAAADijLIgPEkICWgCIgCBWIjkAMIASmGIBNACAH8AyQgIAAgPAHQgXAMgDAWQgCAPAJAHQAHAGAMgCQAQgCAOgJQAegRgLgYQgKgPgQAAIAAAAAA6AQQh3AGhFAHIAAgjIC8gEIAAAaAjNizQgDAMgOASIgJALIgNgDIAHgRQgWgGAAgYQAAgSARgFQASgGAMAMQALAJgEARIAAAAAkhgZQAJAmgFAsQgGArgVAgQgZAkglALQgiAJgbgDQgvgGgXggQgYghAFhGQAGg+AmgpQAfgkA5gBQBSgEAVBLIAAAAAmqgbQgcAmAFBBQAEAzAaAHQAaAIASggQAJgSAEguQABgegBgYQgCgZgPgHQgdgNgSAaIAAAAApXAQQh4AGhFAHIAAgjIC9gEIAAAaAwKgXICEiHIAtA8IhiBlIBaCMIhAAsQgYgsgYgnQgkgzgVghIAAChIhagCIAZmGIBQALIgPCxAz/AMQgKAkACAWQACAeALAIQAZASAYgOQAPgKAageIAiAcQgRAfgPAOQgTATgcAJQgdAKgggIQgggHgTgeQgmg6AihaQAbhGAygPQA4gQAoAfQAUASACAaQAEATgGAfIg/gCIABgcQgBgVgOgBQgPgCgPAPQgOAOgGAXIAAAAA1ygZQAEAZgCAmIgHCJIhVAEIAMgiQgoAfgUAFQgkAJgcgeQgRgSAAgqQAAgiATgcQAagmApgFQASgBAUAFQANACATARQAFglgDgMQgGgPgVAGQgOAEgXAUIgvgpQAigdAPgFQAbgLAbAEQAlAFATAcQAJAQAEAYIAAAAA25BBQgJgPgRAAQgIAAgPAHQgWALgEAXQgCAPAKAHQAHAGALgCQAQgCAOgJQAfgRgMgYIAAAAA5tAZQgKBkg2AjQgeAUglADQgjABgXgLQgggOgLgfQgKgYgDgpIBMgEQADAkAUALQAPAKATgMQASgLAMgkQAJgfAAhIIACihIBPACIAAB6QAAAggIBMIAAAA").cp();
	this.shape_1.setTransform(189.2,21.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,378.9,40.2);


(lib.grLantern = function() {
	this.initialize();

	// rLantern and hand
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B5B5B6").s().p("AB1jcQgagHglgFQhPgMg9AMQg9AMg6AhQgcARgRAOQgFgSAMggQAXg5B/gTQB6gTA0AmQAeAXAGAUIAAAAAD8C7IgyAlQhHAqhXAPQhVAQhCgQIgrgRQAAgHAAgHQAAgUARgeIAKgOIAOAHQBFAZBIgRQBKgQA5gvIAPgOQAMAGASAKQAdARAPAeIAAAA").cp();
	this.shape_2.setTransform(25.7,58.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CBBE00").s().p("ABFgkQAAABAAABQABAbgBAYQgnANgdAIQgQAFgYACQgPgWgOgXQgBAAAAAAQAEgGAGgHQASgUAagHQAZgHAiAFQAOADALADIAAAA").cp();
	this.shape_3.setTransform(28,71.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0075C2").s().p("AgFAlQgEgCgEgEQgPgMgBgTQgBgRAHgLIAIgIIAAANQADAOAKAGQARAHAFAFQAIAHACAMQgLACgMADQgHACgFACIAAAA").cp();
	this.shape_4.setTransform(24.2,55.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E60013").s().p("AAlBHQgCgLgIgIQgFgFgTgJQgIgFgDgOIAAgNIgIAHQgHALABAUQABATAPAMQAEADACACQgMAEgMADQgCgCgCgCQgRgSgJgXQgKgYAIgNQANgJAGgFQAKgIACgMQACgNgLgFQgJgEAAgSIACgRIAGAOQAJAPAJACQAUAFAJADQASAIgBALQAAADgEAQQgCAJADAGQACAHATAIQAPAMgBAiQgLACgNACIAAAA").cp();
	this.shape_5.setTransform(23.5,51.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BAE3F9").s().p("ABEBIQACghgPgNQgTgIgDgHQgDgIACgGQAEgRABgCQABgMgTgHQgJgEgTgFQgKgCgIgPIgGgOIgDARQAAASAKAFQAKAFgCAMQgCAMgKAIQgGAEgNALQgIAMAKAYQAKAYAQASQACACACACQgdAIgPAIQgug9AAgSQAAgBAAgBQACgKAXgUQAagXgCgKQgBgLgfgTIgdgPQAjgTAqgGQAjgFAmADIgIAVQgIAeAOAIQAJAFArAHQAkAFACAJQAEARgQBHQgPABgYAFIAAAA").cp();
	this.shape_6.setTransform(22.8,51);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#898989").s().p("Aj+jOQARgOAcgRQA6ghA9gMQA9gMBPAMQAlAFAaAHQADAHgBAIQgBAGgCAEQgYgGgegFQhVgOg8AQQg9ARg1AiQgPAJgLAJQgJgBgHgFQgIgFgDgKIAAAAAD4CJIAAAAQASAmgbAdQgcAgh1AdQhvAdg6gGQgygGgSgeQgJgPgCgXIArARQBCAQBVgQQBXgPBHgqIAygl").cp();
	this.shape_7.setTransform(26.1,63.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#727171").s().p("AA7gmQARgFASgMQAQAMAAALQAAAdgPAYQgMABgOABQADgWgFgTQgCgMgGgIIAAAAAg/gDQgBAIABALQADARAIAQQgLADgKAEQgGgCgFgEQgVgMgEgVQAVgKASgJQADAAAEgBIAAAA").cp();
	this.shape_8.setTransform(14.8,24.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ACQAmQgagQgUgKQgHgFgHgDQgagLgMgBQgQgCgMAKQgDAEgDADQgBgFgBgCIgVhVIg+gKQAVAVASAhQAIAOAHASQAKAVAIAbQADAQAEAPQgSgJgXgJQgngPgUgDQgIgBgFABQgHABgGADQgKADgHAHQAAABgBAAQgDAEgCADIg8hoIgOAfIBNB2QAGAJAGAJQgNgHgOgFQgqgRgIAIQgHAGAIASQgJgKgLgNIgZghIgJAYIAYAfQAYAeAQAQQgOgCgSgFQgSgFgTAFIgMAFQgKgNgHgPQgbg3ANhAQAThcBsguQBxgvBWACQBTACAWArQARAjAFAoQACAKAAAJQAAAIAAAGQgCAdgDAVIAAAAAEtgVQAAgDgBgBQgFgJgVAGQAAAAAAABQgpALgIAAQgPAAgIgNQgCgEgCgEIgDgUQAbgVAbgEQAngFARAbQANAWgNANQgCACgCACIAAAA").cp();
	this.shape_9.setTransform(11.4,6.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#C9CACA").s().p("AkgBbIANgFQASgGASAFQATAFANACQACACACACQAMALAjAHQASAEAQABQgVAGgWAEQhUAPgkgyQgCgBgBgCIAAAAAiMAsQAUAcAVAPQgQAMgQgDQgVgDgKgEQgPgGgQgMQgJgHgOgQQgIgSAGgGQAJgIAqAQQAOAGANAGIAAAAAgEgCQAEARACASQgEAQgQAIQgRAIgXgFQgJgCgJgEQgFgBgEgCQgqgTgUgiIgIgOQACgEADgDQAAgBABAAQAHgHAKgEQAGgCAHgBQAFgBAHABQAVACAmAPQAXAJAVAKIAAAAAAAhBQACgEADgDQAMgNAQACQANACAaANQAGADAIAEQATALAaAQQgDASgEAKQgGAQgNAKQgMAJgQADQgCAAgBAAQgaAEgTgLQgLgcgSg+IAAAAAEhhgQgCABgCABQgNAJg1AYQgmAUgcAaQAEgPACgSIABhBQADgDADgDQAIgHAIgGIAEAUQABAFADADQAHANAQAAQAHAAApgLQAAAAABAAQAUgGAFAIQABACABACIAAAA").cp();
	this.shape_10.setTransform(12.6,13.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFF100").s().p("AmplRQAOAbAZAUQA8AwBkghQAKgEAKgDQADASANAWQACAEACADQgxAbgMAlQgTA9AXAjQALARAQAGIBPEKIgPA1QgHA+AjArQAnAwBOABQA4ABBmgcQBUgWAxgqQAwgpAAgsQAAgkgqguIgdgaIhCkZQAEgWgIgbQgOg2g0gZQgWgKgdgEQAAgigOgnQgFgQgRgLQAEgFADgGQAlgcA4gUQBAgWAVgXQAKgLAEgOQA1AJAzASQDpBOBADFQBBDGiODGQiNDJkJBXQkGBWjphOQjphPhAjFQhBjFCOjHQA5hSBOg+IAAAAAgslbQADABADAAQALAIAEASQAFARgCAUQgcADggAIQgPADgNAEQgJgPgDgQQgCgMACgJQAUgHAQgOIANgPQAFAAAEAAIASAGAiphSQALgOATgPQABgBACAAIASALQAZARAFAHQAEAFgRAXQgUAaAAANQAAAPAaApQALARALAQQABARAbA6QAMAZAMAWQgRAAgUAAIgYgCIhXkZABBiYQAOACAPADQAeAGAWAHIA5EUQgYAJgWAJQgEh/gNgMQACgPABgRQABgngJgZQgHgWgdgHQgggIgGgGQgKgMAJgPIAFgHAgLCYQgfg2AIgLQAKgNA+gRQA/gRANAHQALAGACA/QgLgDgOgDQgigFgbAHQgaAHgQAUQgGAHgEAGIAAAA").cp();
	this.shape_11.setTransform(22.2,55.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231916").s().p("AEnl7QgEAOgKAKQgVAXhAAXQg4ATglAcQgDAGgEAGQARALAFAQQAOAnAAAiQAdADAWALQA0AYAOA2QAIAbgEAWIBCEZIAdAbQAqAuAAAjQAAAtgwAoQgxAqhUAXQhmAcg6gBQhMgBgngwQgjgsAHg9IAPg1IhPkNQgQgFgLgSQgXgjATg6QAMgmAxgaQgCgEgCgDQgNgWgDgTQgKAEgKADQhkAhg8gwQgZgTgOgbQgVgmgBg0QgChaA7g6QA9g7BcggQBegiBSALQBBAJAiA3QARAcADAaQAIgIAMgIQAYgSAXgGQAggJAmATQAoAVADAkQACAQgDANIAAAAAD7l+QACgCACgBQANgOgNgVQgRgbgnAFQgbADgbAVQgJAGgIAHQgDADgCADIgCBBQgCASgDAPQAcgaAlgUQA1gYAOgJQACgBABgBIAAAAAgklfQASA+AMAeQAQALAagEQACAAACAAQAQgDAMgJQAMgKAHgSQAEgKADgSQADgVACggQAAgGAAgIQAAgIgCgLQgFgogRgiQgWgshRgCQhYgChxAwQhsAtgTBfQgNA/AbA4QAHAOAKAOQABACABABQAlAyBUgPQAWgEAUgGQgPgBgTgEQgigHgMgLQgCgCgCgCQgQgQgYgeIgYgeIAJgYIAZAgQALAOAJAKQAOAQAJAHQAQAMAQAGQAKAEAVADQAPADAQgMQgUgPgVgcQgGgIgGgJIhNh5IAOgfIA8BrIAIAOQAVAkAqATQAEACAEABQAJAEAJACQAYAFARgIQAPgIAHgQQgEgSgFgTQgEgPgFgQQgIgcgKgXQgHgRgIgPQgSghgVgVIA+AKIAXBVQABAFABAFIAAAAAArjVQAGAIACAMQAFAUgDAXQAOgCAMAAQAPgbAAgcQAAgMgQgMQgSANgRAFIAAAAAhPiyQgEAAgDAAQgSAMgVAKQAEAUAVANQAFADAGADQAKgEALgDQgIgQgDgSQgBgLABgJIAAAAAAMjTIgQgHQgEAAgFABIgNAPQgQAOgUAGQgCAJACAMQADAQAJAPQANgDAPgEQAegHAcgEQACgTgFgSQgEgRgLgJQgDAAgDAAIAAAAADTg2QgGgUgfgXQgzgmh7ATQh/ATgWA5QgNAgAFAQQADAKAJAFQAHAFAJABQALgJAOgJQA2ggA6gRQA9gQBXAOQAdAFAYAGQACgEABgGQABgIgCgHIAAAAAhvA0IBXEbIAYABQASABARAAQgMgXgMgZQgZg5gBgSQgLgPgLgSQgagpAAgQQAAgOAUgaQARgXgEgFQgFgGgZgRIgSgMQgCABgBABQgTAPgLAOIAAAAAAtC0QAMgDAPgEQAGgCAHgBQANgDALgDQAMgCALgCQAYgFAPgBQAQhJgEgRQgCgKgkgFQgrgGgJgGQgOgIAIgdIAIgTQgogEgjAFQgoAGgjASIAdAPQAdATABALQACAJgYAYQgXAWgCAKQAAAAAAABQAAASAsA+QAPgIAdgJIAAAAAB7gQIgFAGQgJANAKAMQAGAHAgAIQAdAGAHAXQAJAYgBAnQgBAUgCAOQANANAEB+QAWgIAYgKIg5kVQgWgGgegGQgPgDgOgBIAAAAAC5D8QgChAgLgFQgNgHg/ARQhAAQgKANQgIALAfA2QAAABABAAQAOAYAPAXQAYgDASgEQAdgIAngOQABgagBgaQAAgBAAgBIAAAAAg4GuQACAXAJAPQASAeAvAGQA6AGBygdQB0gdAdggQAagdgRgmIAAAAQgPgegdgRQgSgKgNgGIgOAOQg5AvhKAQQhKARhEgZIgOgHIgJAOQgSAeAAAUQAAAHABAHIAAAA").cp();
	this.shape_12.setTransform(16.4,42.2);

	this.addChild(this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-43.6,-13.4,131.8,121);


(lib.grJack = function() {
	this.initialize();

	// jack
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E4007F").s().p("ACrAMQgRgQgmgeIgngfQg5ACgiABIhNADQgPAOgRAQQgfAdgRAPQAHALAAAOQAAATgOAOQgOAOgUAAQgUAAgNgOQgOgOAAgTQAAgUAOgOQANgMAUAAQALAAAJAEQAKgHAKgIQAjgaAVgPIhoAEIBDgQQBQgQA/AAQBjAACQASQhOACg7ABQAeAOBCAsQANgHAQADQATADAMAOQALARgDASQgEAUgQAMQgQALgTgEQgUgDgLgRQgLgPADgUQABgHAEgGIAAAA").cp();
	this.shape_13.setTransform(4.2,38.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#38003B").s().p("ALbhiQAFABAGABIgmA3QgmBGApAWQBNATBBA/QAYAWAQAVQgcACgtgFQhtgOglAQQhWAkgmANQhJAYg2AAQgiAAiDggQh+gfg/AEQglACjDAxQi2AshmgDQiDgFiWgpQiTgngIgeQgGgaAogIQAigHAWAJQAbAMA0ANQBCAQAXgIQAPgGAHgxQAHgxAagMQAXgLApAbQAyAhA0AAQBEAABTgxQBGgqAqgwQAwg5CAi4IBOCDQBbCKA+AhQBEAlBGgIQA3gHAsggQARgMAhg0QAagqAngJQArgLBKAQIAAAA").cp();
	this.shape_14.setTransform(-1.4,72.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#5C0060").s().p("Ap0lkIAmAAQBbABA+AOQAFABAEABQBOARBUAmQAYAKASAJQA1AdgEARQgEAUhHgGIgrgHQhBguiNg1IiBgtAssFIQAqiYBqh2QBohxBdgNQgQAIgRAOIgKAGQg0AogrA7QglA1gfBRQgQAogIAeQgHARgEAbQgGAugOAEQgQAEg3gbQgHgDgGgDIAAAAAn6D9QAYgvAfgxQBGhzAqgZQAqgWAwAqQAUASANAVQgsA0gYAVQhNBBgsAWQg5AdgsgMIAAAAAHtBYQgCABgCABQgQAIgPARQgRATgKAKQghAgg2AJQhiiRgRglQgGgMAgAAQAhABAwAMQB2AgAnA0IAAAAAJRllIlJCLQADgBADAAQgGABgGACQgnAHgTgOQgUgPA9gnQA7glA9gOQARgEAVgEQANgBALgDQBDgJBngIIAAAAAMtE3QgagTgkgRQhagkgMgMQgOgNAtgwQAXgYAZgVQgahPhbhLQgCgCgDgCIANAHQBJArAkAvQAjAvAgB9QALApAHAmIAAAA").cp();
	this.shape_15.setTransform(5.3,52.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#7F1184").s().p("AJzlfQhnAHhDAKQgMACgMABQgWAEgQAEQg9AOg7AlQg9AnAUAPQASAOAngHQAHgBAGgCQBvgLB1AhQB3AiA8A8QA+A+BMC4QBMC6gZAjQgUgcghgZQgIglgKgqQggh9gkgvQgjgvhJgrIgNgHQhShDg7gIQBQAqBDBGQAhAkASAbQgfAAglAEQhFAGghAPQgngzh3ghQgwgMgggBQghAAAHAMQARAmBiCQQgGABgGAAQhMAIgwgaQgqgXgkg7Qgcgvg+hzIg4htQgvBEg6BMQg4BHgnAvQgOgWgTgSQgwgqgqAWQgqAZhGBzQgfAygYAuQgKgDgJgFQg3gegjgBQgTAAgTAIQAShhBRhnQAcghAgggIAbgZQheANhnBxQhqB2gqCYQgzgXgXAAQgXAAgeAMQAVhRAmhcQBRi/Blg8QCEhQBJgSQBbgWB/AdQgJgGgJgHIAqAGQBHAGAFgUQAEgRg2gcQgSgKgXgKQhVglhNgSQgFgBgEgBQg/gOhbgBIglABIgTgHIBEgHQBVgFBRAGQEEASB/B2QCdh5D9gRQB/gIBgAQIgOAGADBh7QgDAGgBAIQgEATAMAQQALAQATAEQATADARgLQAQgMADgTQAEgTgMgQQgLgQgTgEQgQgCgOAHQhBgsgegPQA6gBBOgCQiQgRhkAAQg9AAhQAQIhEAQIBpgEQgVAOgkAbQgKAHgJAIQgKgFgKAAQgUAAgOAOQgOAOAAAUQAAATAOAOQAOAOAUAAQATAAAOgOQAOgOAAgTQAAgOgGgKQARgSAfgdQAQgPAQgOIBKgDQAkgCA6gBIAmAeQAmAfARARIAAAA").cp();
	this.shape_16.setTransform(1.9,51.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.rf(["#E5005A","#E60013","#EA5506","#E55309","#D24B0F","#B33F14","#8A2F13","#571B0D","#220001","#000000"],[0,0.416,0.737,0.761,0.796,0.831,0.871,0.914,0.957,1],-1.7,-10.2,0,-1.7,-10.2,51.1).s().p("Ai4AuIALgJIBVBXIBXhXIBbBJIBChQIByBXIF+i4QhABIhKBNQhlBpg1AoQgYASgPAFQgBAAgCAAQgsANgjgSIgagVQgOASgUASQgWAUgTAJQgPAIgNAAQgDAAgCgBQgcgCgpgdIgkgfQgMAPgWAOQgrAegvAAQghAAgbgRQgLgHgKgJIgNgRIgMgQQgDANgOALQgcAXgzgEQgmgEhZhZQgVgUgXgZQgKgMgMgMIiEiaICcBIIAkARICrBSIBkhMIAEgDAHFiAQgJARgLANQgfAlgoAHQhJAOgxhMQgQgYgLgeIgIgZIC2g8IArgOIBOgbIgGAjQgJAqgOAkQgMAggOAXIAAAA").cp();
	this.shape_17.setTransform(3.1,-36.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.rf(["#E5005A","#E60013","#EA5506","#E55309","#D24B0F","#B33F14","#8A2F13","#571B0D","#220001","#000000"],[0,0.416,0.737,0.761,0.796,0.831,0.871,0.914,0.957,1],40.6,7.3,0,40.6,7.3,51.1).s().p("AgihSIAOAEICsA2QgJAngZAnQgwBMhIgMQgigFgdgdQgLgLgJgPQgTgbgQgmQgPgjgJgqIgHgjIB1Al").cp();
	this.shape_18.setTransform(-35.3,-54);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.rf(["#E5005A","#E60013","#EA5506","#E55309","#D24B0F","#B33F14","#8A2F13","#571B0D","#220001","#000000"],[0,0.416,0.737,0.761,0.796,0.831,0.871,0.914,0.957,1],0.8,4.6,0,0.8,4.6,51.1).s().p("AgwA5IgeAKIBOiFIBPCCQgmgSgiAAQgUAAgjALIAAAA").cp();
	this.shape_19.setTransform(2.1,-51.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#C3D94E").s().p("AgWguIATgNIAaB2IgYABIgVhq").cp();
	this.shape_20.setTransform(4.7,-98.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#8FC31F").s().p("AhdgwQgJgLAWgYQAWgZAXgFQAYgGANAFQATAFANAVQAMAUAHAnQACAKAIA1QADAXAcAaQADACADADQgKAFgJAKIgLAPQgIgGgNgGQgZgNgWAAQgTAAgfANIgaAMQgLgNgOgLIAdgdQAjgoACgZQADgpgPgsQAAALgHAXQgCAIgDAKQgagEgKgLIAAAAAAChOIAVBqIAagBIgch2IgTAN").cp();
	this.shape_21.setTransform(2.1,-94.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFF462").s().p("Aooi7QA5gkA8gUQAOgFANgEQAHAEADAGQAIARhUAZQhRAZADgMIAAAAACJjXIgTgCQgMAAgKgDQgVgGAHgQQAHgPAwADQA0ACAxAXQA9AdBTBWQBgBjAcBUQAjBpAIAkQALAugPAAQgGAAgKgkQgUhDgHgUQgxiOhYhPQhZhRhYggQgbgKgYgEIAAAAAmHjQQAqgWAeAJQAdAJATAXQATAXgEATQgDATgQAFQgRAFAAgQQAAgRgYgUQgYgVgXAAQgSAAglAYQgdAUADgHQAJgfAsgWIAAAAAD2AEQgUgmghgoQg6hEg1gTQgpgNgpgHIgfgEIAhgPQAsgKA0AYQBVAnAvAwQAnAoAUAzIgrAMAEkChQALgNAKgQQACA5gLgIQgGgEgGgQIAAAAAhXiVQAaATADARQACAKAbBqQAVBogXAGQgTAEgJhUQgLhlgUgdQgagkgwgLIgrgDIARgOQAWgNAZACQAdADAbAUIAAAA").cp();
	this.shape_22.setTransform(17.1,-62.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#231916").s().p("ArliSQgZh5AsiFQBWkICxiKQCyiLDXAgQAJgLAIgOQABgFACgEQgNgHgMgKQgggaAGgXQAHgcAdgWQAdgVAggCQAegCASALQARAJAOAbQALAVAHAmQAKAzAAABQABAEACAEQBigfBsAaQBwAaBkBTQBmBUBFB+QBJCGAWCgQAqEvjLCAQAZACAZACIAqA3QiNAwh3A4QBtANBYAmQBXAlArAyQA6BFBODBQBYDagvArQgoAkhVgQQgwgKgagEQgsgGgjAGQgxAIg+AsQhAAthRAPQhUAQiEg5QhagmgHgDQg0gTgiABQgiACg2AUQhHAcgpAPQigA9iDgHQiZgHjGhJQhMgdg0gbQgzgbABgKQABgDACgEQAhhfA0hsQBtjgBkhHQBlhHBxghQA4gRAkgDIkNhtIA2gzIAggBQgwgfgogxQhEhPgVhqIAAAAAp4gjQAOAVARARQA0A5BBAYQA/AWAygQQAHARAIAPQABAAACAAQDsARB6BFQA1gLAcgmQAMAMANAKQBIgiBpgQQAEgMABgMQAkATBOgIQBZgJBMgqQBGgmAqg2QBXhzgYi8Qgmksi8ihQiziZjcArQAKAPARASQAQAAAUAHQAQAGAMAGQgHgDgMAAQgXgBgTALQgTALgOAXIgKAWQgNgLgTgKQgkgVgcAAQgaAAgVAVIgQAVQgFgJgKgMQgTgZgXgRQgXgSgiAEIgcAHIAegPQAdgLAUAGIAMgEQAHgEAHgGQhHgLhOAWQgOADgNAFQg9AUg5AkQggAVgfAaQi/CdgvDsQgpDMBbCGIAAAAAhIvmQAJAMAbAEQADgKACgIQAHgXAAgMQAPAsgDAqQgCAbgjAoIgdAdQAOALALAMIAagMQAdgMAVAAQAWAAAZAMQANAGAIAGIALgPQAIgJALgFQgDgDgDgDQgcgagDgWQgIg3gCgLQgHgngMgTQgNgVgTgGQgPgEgWAFQgXAGgWAYQgWAZAJAKIAAAAAKHCkIANgGQhfgQh/AJQj+AQicB5QiAh2kEgSQhRgFhUAFIhFAGIAUAHICBAsQCMA1BBAvQAKAHAIAHQh+gehbAXQhKASiDBPQhlA9hRDBQgnBcgUBQQAegMAXAAQAXAAAyAYQAGADAHADQA4AbAPgEQAPgEAGguQADgbAHgRQAJgeAPgpQAghRAlg0QArg9AzgoIAKgHQARgNAQgJIgaAZQggAggcAkQhRBngTBhQATgIATAAQAkABA2AdQAJAFAKADQAsANA5gdQAsgXBNhAQAYgVAsg0QAogvA3hIQA7hMAuhEIA5BsQA9B2AcAuQAkA8AqAXQAwAaBMgIQAGgBAGgBQA3gIAgggQAKgKARgUQAQgQAPgIQACgBACgBQAhgQBGgGQAlgDAeAAQgRgcgigkQhDhIhPgpQA7AHBRBDQADADADACQBaBNAbBOQgaAVgXAYQgtAwAOAOQAMALBbAkQAjARAaATQAiAZATAcQAagjhMi6QhNi6g+g9Qg8g9h3ghQh1ghhvALQgDAAgDAAIFKiKALNJyQhKgQgrALQgnAJgaAqQgiA2gQAMQgsAgg4AHQhGAIhDglQg+gjhbiKIhOiDQiAC4gwA5QgrAyhFAqQhTAxhEAAQg0AAgzghQgpgbgXALQgaAMgGAxQgHAxgQAGQgWAIhDgQQg0gNgbgMQgVgJgjAHQgoAIAHAaQAIAeCTAnQCVApCDAFQBmADC2gsQDEgxAlgCQA+gEB+AfQCDAgAiAAQA3AABIgYQAmgNBWgkQAmgQBtAOQAsAFAcgCQgQgUgXgXQhCg/hMgTQgpgWAlhIIAmg3QgFgBgFgBIAAAA").cp();

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#D07100").s().p("Am8i/IgBAGQgIA/gBBCIgjgQQAEg6ANg8IAHgaQAKAOALALIAAAAABuDEQADAAACAAQANAAAPgHQgCAUgDAUQgGAqgNBUQgBAFgBAGQAlASA2gSQAngMAbgYQAghaAMg5QADgPADgSQABgBACAAQAOgFAYgSIgVCsQAbAPApgBQBCgBA0gnQAxglAsgFQAZgCALAJQgrA4hFAmQhMAqhaAJQhNAIgkgTQgBAMgFAMQhpAQhIAiQgMgKgNgMQgbAmgzALQh9hFjsgRQgBAAgBAAQgJgPgHgRQgxAQg/gWQhCgYgzg5QgSgTgOgVIALAHQAcARAcALQBMAfA0gRQgXiFgFhvQAAAAAAgBQAXAZAUAVQAMBfAmB5QAHAXAHAVQAZATAgAMQBRAfA6gxQgCgMgCgNQgPhugFhIIANAQQAJAJALAHQAMBFAYBjQADAOAEAOQA0AjA3ABQBFACAmg5QARhLAJgqQAEgTACgUIAAAAAizg1IgEADQgEgNgGgzQgEghAEgmQABgTAIg0QAGghAQgyQAQgwADABQABAAgKA5QgNBJgEAkQgFAngCBLQgCAngBAOIAAAAAmPljIgOgEQAMgcAIgNQALgUAXgbQAWgaACACQABABgOAXQgYAlgKARQgJAQgIAWIAAAA").cp();
	this.shape_24.setTransform(2.5,-26.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.rf(["#FABE00","#F39800"],[0,1],-4.3,-18.3,0,-4.3,-18.3,65.5).s().p("AqVFaQhaiGAojMQAvjqC/idQAggaAggVQgCAMBQgZQBUgZgIgRQgDgGgHgDQBPgWBHALQgHAGgIAEIgLAEQgUgGgeALIgeAPIAdgHQAhgEAXASQAXARAUAZQAJAMAFAJIAQgVQAWgVAbAAQAaAAAlAVQASAKANALIALgWQAOgXATgLQATgLAXABQALAAAIADQgMgGgQgGQgVgHgPAAQgRgTgLgOQDdgrCyCZQC9ChAmEqQAYC8hXBzQgLgJgZACQgsAFgxAlQg0AnhCABQgpABgagPIAVisQA1gnBlhqQBJhNBBhIIl+C4IhzhXIhBBQIhdhIIhVBWIhWhWIgLAIQABgOACgnQAChJAFgnQAEgkANhJQAKg5gBAAQgDgBgQAwQgQAygGAhQgIA0gBATQgEAmAEAfQAGAzAFANIhkBMIishSQABhAAIg/IABgGQAdAdAiAFQBKAMAwhMQAZgnAJgpIiug2QAIgWAJgQQAKgRAYglQAOgXgBgBQgCgCgWAaQgXAbgLAUQgIANgMAcIh1glIAHAjQAJAqAPAjQAQAoATAcIgIAaQgMA8gFA4IidhJICFCaQALANALALQAAABAAAAQAFBvAXCFQg0ARhMgfQgcgLgcgRIgLgHAEYnKQAYAEAbAKQBYAgBZBRQBYBPAxCQQAHAUAUBDQAKAiAGAAQAPAAgLgsQgIgkgjhpQgchWhghjQhThWg9gdQgxgXg0gCQgwgDgHAPQgHAQAVAGQAKADAMAAIATACAj4nDQgsAWgJAfQgDAHAdgUQAlgYASAAQAXAAAYAVQAYAUAAARQAAAQARgFQAQgFADgTQAEgTgTgXQgTgXgdgJQgegJgqAWIAAAAAGFjtIi2A8IAIAZQAMAeAPAYQAyBNBJgOQAogIAfglQAGAQAFAEQALAIgCg5QAOgYAMgfQANglAJgqIAHgiIhPAaQgUgzgngoQgvgwhVgnQg0gYgsAKIgjAPIAhAEQApAHApANQA1ATA6BEQAiAoATAoIAAAAAA2mIQgbgUgbgDQgZgCgWANIgRAOIArADQAuALAaAkQAUAdALBnQAJBUATgEQAXgGgVhoQgbhsgCgKQgDgRgagTIAAAAAg3hHQAjgLAUAAQAiAAAmATIhPiEIhOCHIAegLAjXEGQAGBIAOBuQACANACAMQg6AxhRgfQgggMgZgTQgHgVgHgXQglh5gMhfQBZBYAmAEQAyAEAcgXQAOgLAEgNIAMARABsE7QgDAUgEATQgJAqgRBLQgmA5hFgCQg2gBg1gjQgEgOgDgOQgYhjgMhFQAcARAhAAQAvAAArgeQAVgOAKgPIAmAfQAqAdAcADIAAAAACNE0QATgJAWgVQATgSAOgSIAbAVQAjASAsgMQgDASgDAPQgLA5ggBaQgbAYgoAMQg2ASglgSQABgGABgFQANhUAGgqQADgUADgUIAAAA").cp();
	this.shape_25.setTransform(2.8,-38.2);

	this.addChild(this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98.5,-108.3,197.1,216.7);


(lib.grButtonBase = function() {
	this.initialize();

	// レイヤー 1
	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("Egx0gfTMBjpAAAMAAAA+nMhjpAAAMAAAg+n").cp();
	this.shape_26.setTransform(0,0,1.003,0.998);

	this.addChild(this.shape_26);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-319.9,-199.9,640,400);


(lib.mcJackLantern = function() {
	this.initialize();

	// lantern
	this.instance = new lib.grLantern("synched",0);
	this.instance.setTransform(-73.8,90.4,1,1,0,0,0,22.2,47);

	// jack
	this.instance_1 = new lib.grJack("synched",0);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-139.8,-108.3,238.4,259.2);


(lib.mcButtonBase = function() {
	this.initialize();

	// レイヤー 1
	this.instance_2 = new lib.grButtonBase("synched",0);

	this.addChild(this.instance_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-319.9,-199.9,640,400);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;